name: dev

services:
  app:
    build: .
    image: app
    container_name: app
    volumes:
      - static:/app/.static
    command: gunicorn
    depends_on:
      - postgres
    environment:
      - ALLOWED_HOSTS=localhost
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    restart: always

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    image: nginx:modified
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - static:/www/static/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      - postgres

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    depends_on:
      - postgres

volumes:
  postgres:
  static:
