name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        ALLOWED_HOSTS: "*"
        DATABASE_URL: "sqlite:///:memory:"
        DEBUG: 0
        SECRET_KEY: "testing"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pip install -r requirements/test.txt
          python app/manage.py collectstatic --noinput
          python app/manage.py test app
